# Generated by Django 5.2.13 on 2026-07-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSpace',
            fields=[
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('space_id', models.AutoField(db_column='spaceId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_column='isArchived', default=False)),
            ],
            options={
                'db_table': 'RESEARCH_SPACE',
                'ordering': ['space_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('user_id', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='passwordHash', max_length=255)),
                ('full_name', models.CharField(db_column='fullName', max_length=255)),
            ],
            options={
                'db_table': 'USER',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('share_link_id', models.AutoField(db_column='shareLinkId', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('expires_at', models.DateTimeField(blank=True, db_column='expiresAt', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('space', models.ForeignKey(db_column='spaceId', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='app.researchspace')),
                ('created_by', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to='app.user')),
            ],
            options={
                'db_table': 'SHARE_LINK',
                'ordering': ['share_link_id'],
            },
        ),
        migrations.AddField(
            model_name='researchspace',
            name='owner',
            field=models.ForeignKey(db_column='ownerId', on_delete=django.db.models.deletion.PROTECT, related_name='owned_spaces', to='app.user'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('item_id', models.AutoField(db_column='itemId', primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('image', 'Image')], db_column='itemType', max_length=20)),
                ('content_text', models.TextField(blank=True, db_column='contentText')),
                ('source_url', models.CharField(blank=True, db_column='sourceUrl', max_length=500)),
                ('image_path', models.CharField(blank=True, db_column='imagePath', max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('source_platform', models.CharField(choices=[('web', 'Web'), ('extension', 'Extension')], db_column='sourcePlatform', max_length=20)),
                ('captured_url', models.CharField(blank=True, db_column='capturedUrl', max_length=500)),
                ('page_title', models.CharField(blank=True, db_column='pageTitle', max_length=255)),
                ('space', models.ForeignKey(db_column='spaceId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.researchspace')),
                ('added_by', models.ForeignKey(db_column='addedBy', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.user')),
            ],
            options={
                'db_table': 'ITEM',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('request_id', models.AutoField(db_column='requestId', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(db_column='requestedAt')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='resolvedAt', null=True)),
                ('space', models.ForeignKey(db_column='spaceId', on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='app.researchspace')),
                ('requester', models.ForeignKey(db_column='requesterId', on_delete=django.db.models.deletion.PROTECT, related_name='requested_collaborations', to='app.user')),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolvedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_collaborations', to='app.user')),
            ],
            options={
                'db_table': 'COLLABORATION_REQUEST',
                'ordering': ['request_id'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token_id', models.AutoField(db_column='tokenId', primary_key=True, serialize=False)),
                ('token_value', models.CharField(db_column='tokenValue', max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('extension', 'Extension')], db_column='clientType', max_length=20)),
                ('issued_at', models.DateTimeField(db_column='issuedAt')),
                ('expires_at', models.DateTimeField(blank=True, db_column='expiresAt', null=True)),
                ('is_revoked', models.BooleanField(db_column='isRevoked', default=False)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='app.user')),
            ],
            options={
                'db_table': 'AUTH_TOKEN',
                'ordering': ['token_id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('membership_id', models.AutoField(db_column='membershipId', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('collaborator', 'Collaborator'), ('viewer', 'Viewer')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], max_length=20)),
                ('space', models.ForeignKey(db_column='spaceId', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.researchspace')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='app.user')),
            ],
            options={
                'db_table': 'MEMBERSHIP',
                'ordering': ['membership_id'],
                'constraints': [models.UniqueConstraint(fields=('space', 'user'), name='uq_membership_space_user')],
            },
        ),
    ]
